defmodule Helpdesk.Repo.Migrations.AddUserSession do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_sessions, primary_key: false) do
      add(:session_uid, :uuid,
        null: false,
        default: fragment("gen_random_uuid()"),
        primary_key: true
      )

      add(:user_id, :bigint)
    end

    create unique_index(:user_sessions, [:session_uid], name: "user_sessions_primary_index")
  end

  def down do
    drop_if_exists(
      unique_index(:user_sessions, [:session_uid], name: "user_sessions_primary_index")
    )

    drop(table(:user_sessions))
  end
end
